name: ufrgs
channels:
  - willyd
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cudatoolkit=11.0.3
  - cudnn=8.0.5.39
  - openssl=1.1.1k
  - pip=21.1.3
  - python=3.7.10
  - python_abi=3.7
  - setuptools=49.6.0
  - sqlite=3.36.0
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - absl-py==0.13.0
    - albumentations==1.0.0
    - anyio==3.2.1
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.32.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - imageio==2.9.0
    - imgviz==1.2.6
    - importlib-metadata==4.6.0
    - ipykernel==5.5.5
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyter-packaging==0.10.3
    - jupyter-server==1.9.0
    - jupyterlab==3.0.14
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - labelme==4.5.9
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.2.2
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclassic==0.3.1
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.0
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opencv-python==4.5.1.48
    - opencv-python-headless==4.5.2.54
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyqt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyrsistent==0.18.0
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pywin32==301
    - pywinpty==1.1.3
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - requests-unixsocket==0.2.0
    - rsa==4.7.2
    - scikit-image==0.18.2
    - scipy==1.6.2
    - send2trash==1.7.1
    - six==1.15.0
    - sniffio==1.2.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.0
    - tensorflow_io==0.17.1
    - termcolor==1.1.0
    - terminado==0.10.1
    - testpath==0.5.0
    - tifffile==2021.6.14
    - tomlkit==0.7.2
    - tornado==6.1
    - tqdm==4.60.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.1.0
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.4.1