name: tensorflow
channels:
  - willyd
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cudatoolkit=11.0.3
  - cudnn=8.0.5.39
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.7.10
  - python_abi=3.7
  - setuptools=49.6.0
  - sqlite=3.35.3
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cachetools==4.2.1
    - chardet==4.0.0
    - colorama==0.4.4
    - cycler==0.10.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - imgviz==1.2.6
    - importlib-metadata==3.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - labelme==4.5.7
    - markdown==3.3.4
    - matplotlib==3.2.2
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - pillow==8.2.0
    - protobuf==3.15.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.8.1
    - python-dateutil==2.8.1
    - pyyaml==5.4.1
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.6.2
    - six==1.15.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
