name: mis
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cudatoolkit=11.2.0
  - cudnn=8.1.0.77
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.7.16
  - setuptools=65.6.3
  - sqlite=3.41.2
  - wheel=0.38.4
  - pip:
    - absl-py==1.4.0
    - albumentations==1.3.0
    - astunparse==1.6.3
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - colorama==0.4.6
    - contourpy==1.0.6
    - cryptography==39.0.2
    - cycler==0.11.0
    - efficientnet==1.0.0
    - flatbuffers==23.3.3
    - fonttools==4.38.0
    - gast==0.4.0
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.3
    - h5py==3.8.0
    - idna==3.4
    - image-classifiers==1.0.0
    - imageio==2.26.1
    - imgviz==1.7.2
    - importlib-metadata==6.1.0
    - joblib==1.2.0
    - keras==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - labelme==5.1.1
    - lazy-loader==0.2
    - libclang==15.0.6.1
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.5.3
    - msal==1.21.0
    - natsort==8.3.1
    - networkx==2.6.3
    - numpy==1.21.6
    - oauthlib==3.2.2
    - opencv-python==4.5.1.48
    - opencv-python-headless==4.5.2.54
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.3.5
    - pillow==9.4.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyjwt==2.6.0
    - pyparsing==3.0.9
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qtpy==2.3.0
    - qudida==0.0.4
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - segmentation-models==1.0.1
    - six==1.16.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - zipp==3.15.0